NDefines.NAir.AIR_WING_MAX_STATS_SPEED = 2500
NDefines.AIR_WING_MAX_STATS_BOMBING = 300

NDefines.NAir.COMBAT_DAMAGE_SCALE = 0.7
NDefines.NAir.COMBAT_DAMAGE_STATS_MULTILIER = 0.60
NDefines.NAir.BIGGEST_AGILITY_FACTOR_DIFF = 1.75
NDefines.NAir.COMBAT_BETTER_AGILITY_DAMAGE_REDUCTION = 0.36